#----------UNIONS--------
#-----UNION WILL COMBINE ROWS IN THE FIRST TABLE AND DISTINCT ROWS IN THE SECOND TABLE --------



SELECT FIRST_NAME, LAST_NAME
FROM parks_and_recreation.employee_demographics
UNION 
SELECT first_name,last_name
FROM parks_and_recreation.employee_salary;


#----------UNION ALL DISPLAY ROWS IN BOTH THE TABLES---

SELECT FIRST_NAME, LAST_NAME
FROM parks_and_recreation.employee_demographics
UNION ALL
SELECT first_name,last_name
FROM parks_and_recreation.employee_salary;

#---------UNION-----------

SELECT FIRST_NAME,LAST_NAME,'OLD MAN' AS LABEL
FROM PARKS_AND_RECREATION.EMPLOYEE_DEMOGRAPHICS
WHERE AGE > 40 AND GENDER = 'MALE'
UNION
SELECT FIRST_NAME,LAST_NAME,'OLD LADY' AS LABEL
FROM PARKS_AND_RECREATION.EMPLOYEE_DEMOGRAPHICS
WHERE AGE > 40 AND GENDER = 'FEMALE'
UNION
SELECT FIRST_NAME,LAST_NAME,'HIGHLY PAID EMPLOYEE' AS LABEL
FROM PARKS_AND_RECREATION.EMPLOYEE_SALARY
WHERE SALARY > 70000;